// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Xamarin.Web.Data;

namespace Xamarin.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191023175533_initil_db")]
    partial class initil_db
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Xamarin.Web.Data.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Xamarin.Web.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("LastName");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<int?>("RolsId");

                    b.HasKey("Id");

                    b.HasIndex("RolsId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Xamarin.Web.Data.Entities.User", b =>
                {
                    b.HasOne("Xamarin.Web.Data.Entities.Rol", "Rols")
                        .WithMany()
                        .HasForeignKey("RolsId");
                });
#pragma warning restore 612, 618
        }
    }
}
